apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nginx-ingress
    releaseName: nginx-ingress
    namespace: default
    version: 0.12.1
    repo: https://helm.nginx.com/stable